### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by corizzi** [HYPERNETS/libhypstar#1]
Hi Kaspars, 

I ran the following commands :

`git clone https://github.com/HYPERNETS/libhypstar`
`cd libhypstar/ && make lib`
`export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:path_to_libhypstar/build`
`vim python/ctypes_test.py # And replaced by the correct /dev/ttyUSB`
`python3 -m unittest ctypes_test.CtypeTests.test_hw_info`

Got :
`[INFO] Creating serial port (baud=115200, portname=/dev/ttyUSB5)`
`[INFO] Created driver instance 0x55c148aa3790`
`Segmentation fault (core dumped)`

Any idea ?

**Comment by stiebrs** [comment]
I assume Manjaro on host PC?

**Comment by corizzi** [comment]
Yes

**Comment by corizzi** [comment]
Still same issue : 

 python3 -m unittest ctypes_test.CtypeTests.test_capture_spectrum_auto_it_VIS
[INFO]  [2021-01-28T11:01:30] Creating serial port (baud=115200, portname=/dev/ttyUSB5)
[INFO]  [2021-01-28T11:01:31] Created driver instance 0x55a81133c410
Segmentation fault (core dumped)

I have pulled and make lib

**Comment by stiebrs** [comment]
Wait, issue is not closed and I haven't asked for you to test :P
I'm committing so I can pull on our host machine

**Comment by stiebrs** [comment]
Ok, now it seems to work on our host

> [kaspars@HYPSTAR-TARTU1 python]$ python3 -m unittest ctypes_test.CtypeTests.test_capture_spectrum_fixed_it_swir
> [INFO]	[2021-01-28T11:47:54] Creating serial port (baud=115200, portname=/dev/radiometer0)
> [INFO]	[2021-01-28T11:47:54] Created driver instance 0x562975c23ce0
> Spectrum timestamp: 1611834475503 (2021-01-28 11:47:55 UTC)
> Radiometer VIS: 0, SWIR: 1
> Entrance L: 0, E: 1
> Integration time: 100 ms
> Pixel count: 256
> Sensor temperature: -5.22
> Acceleration statistics:
>  	X: -15880 ± 36
>  	Y: -521 ± 48
>  	Z: -481 ± 45
> CRC32: 0x9e5452a8

**Comment by stiebrs** [comment]
@corizzi can you test now please?

**Comment by corizzi** [comment]
It works!
Thanks
