### ISSUE TITLE
Untracked python cache folders

### ISSUE THREAD

**Issue by corizzi** [HYPERNETS/libhypstar#3]
Hi @stiebrs, 

I don't know if we should worry about it but `git status`  returns untracked content :
 
<pre>
On branch main
Your branch is up to date with 'origin/main'.

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	build/
	python/__pycache__/
	python/data_structs/__pycache__/

nothing added to commit but untracked files present (use "git add" to track)
</pre>

Perhaps, we should add these folders in .gitignore ?

**Comment by stiebrs** [comment]
added .gitignore with c++ build and python runtime cache
